#install.packages(c("plyr", "lattice", "lubridate", "sqldf", "DataCombine", "ggplot2", "doBy", "reshape", "reshape2", "data.table", "pROC", "zoo", "smbinning", "woe", "caret", "dplyr", "car",
#"scales", "gridExtra", "vcd", "JM", "latticeExtra", "hexbin", "RMySQL"))
library(plyr)
library(lattice)
library(lubridate)
library(sqldf)
library(DataCombine)
library(ggplot2)
library(doBy)
library(reshape)
library(reshape2)
library(data.table)	 
library(pROC)
library(zoo)
library(smbinning)
library(woe) 
library(caret)
library(dplyr)
library(car)
library(scales)
library(gridExtra)
library(vcd)
library(JM)
library(latticeExtra)
library(hexbin)
#library(RMySQL)
library(psych)